name: vms_resident_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  font_awesome_flutter: ^10.7.0 
  url_launcher: ^6.2.1 
  path_provider: ^2.1.2
  share_plus: ^10.0.0
  screenshot: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true